### ISSUE TITLE
Verification step failure

### ISSUE THREAD

**Issue by arey** [loganmzz/rust-installation#2]
Hi Logan,

I've installed Rust with ```rustup``` then I've cloned your repo.
Here my error:
```
MacBook:rust-installation arey$ cargo run
error: failed to read `/Users/arey/Dev/rust-installation/01-basic/Cargo.toml`
Caused by:
  No such file or directory (os error 2)
```
These error gone when I remove the ```members``` property from the root ```Cargo.toml```.

See you tomorrow at Devoxx France ;-)

Antoine

**Comment by loganmzz** [comment]
Thank you for feedback ! It's now fixed. As you may expect, project defintion (Cargo.toml) comes from workshop. Glad to see you later ;)
